version: '3.1'
services:
  db:
    image: postgres:9.6.23-alpine3.14
    ports:
      - 5416:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    volumes:
      - /db/data-dime:/var/lib/postgresql/data

volumes:
  postgres_data:
