version: '3.1'
services:
  db:
    image: postgres:14
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
